# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_jap', models.CharField(max_length=300)),
                ('img_offset', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_jap', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_jap', models.CharField(max_length=300)),
                ('ext_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='words.Base')),
            ],
        ),
        migrations.AddField(
            model_name='subword',
            name='ext_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='words.Word'),
        ),
    ]
