# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-08 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('file_name', models.CharField(max_length=300)),
                ('onYomi', models.CharField(blank=True, max_length=300)),
                ('kunYomi', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
