# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-08 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_kanji'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanji',
            name='name',
            field=models.CharField(default='', max_length=5),
        ),
    ]
